service: finance

plugins:
  localPath: "../node-modules"
  modules:
    - serverless-plugin-ifelse
    - serverless-prune-plugin
    - serverless-dotenv-plugin
    - serverless-offline # This should be the last in the list
custom:
  dotenv:
    basePath: ../
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${env:REGION,'eu-central-1'}
  stackName: ${self:service.name}Stack
  apiName: ${self:service.name}Api
  environment:

  endpointType: regional 
  tags:
    uservice: Finance
  iamRoleStatements: 
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:DeleteItem"
      Resource:
        - arn:aws:dynamodb:${env:REGION,'eu-west-2'}:${env:ACCOUNT_ID}:table/invoices
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*" # 
    
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - arn:aws:lambda:${env:REGION,'eu-west-2'}:${env:ACCOUNT_ID}:function:usersProfiles-ResponseManager-${self:provider.stage}

# you can add packaging information here
package:
  excludeDevDependencies: true
  include:
  #   - include-me.js
  exclude:

functions:
  generatePdfInvoice:
    handler: src/invoicePdfGeneration.handler
    name: invoice-pdf-generation
    timeout: 10
    versionFunctions: true 
    memorySize: 128
    environment:
      invoicesTableName: invoices
      invoiceBucketName: jxh-invoices-pdf-bucket
      invoiceQueue: https://sqs.${env:REGION,'eu-west-1'}.amazonaws.com/${env:ACCOUNT_ID}/invoice-pdf-generation
    events: 
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - invoice-pdf-generation

# you can add CloudFormation resource templates here
resources:
 Resources:
  InvoicePdfBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: jxh-invoices-pdf-bucket
  InvoicePdfGenerationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: invoice-pdf-generation
  InvoicesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: invoices
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: invoiceId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: invoiceId
          KeyType: HASH 
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: "ALL"
  OrdersTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: orders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH 
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: "ALL"

