service: testawscoldstart

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  
  region: eu-central-1
  stackName: ${self:service.name}Stack
  apiName: ${self:service.name}Api
  environment:
  endpointType: regional

functions:
  hello:
    handler: src/handler.hello
    memorySize: 128